- id: door_opened_alarm
  alias: "Door Opened Alarm"
  trigger:
    - platform: state
      entity_id: 
      - binary_sensor.0x00158d0002c01de0_contact
      - binary_sensor.0x00158d0002bfedfb_contact
      - binary_sensor.0x00158d0002e22e07_contact
      - binary_sensor.0x00158d0002ebd1b8_contact
      - binary_sensor.0x00158d0002e9eb61_contact
      - binary_sensor.0x00158d0002eb9e8e_contact
      from: 'off'
      to: 'on'
      for:
        minutes: 15
  action:
    - service: notify.door_sensor_notification
      data_template:
        title: 'Fridge door opened duration alert.'
        message: "{{trigger.from_state.attributes.friendly_name}} has been opened for {{trigger.for}}"